name = "e-yar"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next/public"

[env.production]
vars = { NEXTAUTH_URL = "https://e-yar.com" }

[env.preview]
vars = { NEXTAUTH_URL = "https://preview.e-yar.com" }
